#!/bin/sh

#[ -n $DEBUG ] && set -x

IFS=$'\n\t'

usage() {
    SELF="kubemerge"

    cat <<EOF
USAGE:
  $SELF <CONFIG1> [ <CONFIG2> <CONFIG3...>] : Combine CONFIG1, CONFIG2.....
EOF
}

merge_config() {

    export KUBECONFIG="${HOME}/.kube/config"

    if [ -f "${KUBECONFIG}" ]; then
        echo "Creating backup of existing kubeconfig file"
        mv "${KUBECONFIG}" "${KUBECONFIG}".bak 2>/dev/null
    fi

    for i in "${@}"; do
        if [ -f "${i}" ]; then  
            echo "+++  Processing ${i}"
            KUBECONFIG=${KUBECONFIG}:${i}
        else 
            echo "---> Config ${i} does not exists hence skipping"
        fi
    done

    KUBECONFIG=${KUBECONFIG} kubectl config view --flatten >${HOME}/.kube/config

    echo "Kubeconfig files are merged and available at ${HOME}/.kube/config"
}

main() {
    if [ -z "${KUBECTL:-}" ]; then
        if hash kubectl 2>/dev/null; then
            KUBECTL=kubectl
        elif hash kubectl.exe 2>/dev/null; then
            KUBECTL=kubectl.exe
        else
            echo >&2 "kubectl is not installed"
            exit 1
        fi
    fi

    if [ "$#" -lt 1 ]; then
        echo "error: missing config files" >&2
        usage
        exit 1
    fi

    merge_config "${@}"

}

main "$@"
